USE [master]
GO

/****** Object:  Database [LibraryDB]    Script Date: 07/04/2019 09:00:29 ******/
CREATE DATABASE [LibraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibraryDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\LibraryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LibraryDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\LibraryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LibraryDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibraryDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LibraryDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LibraryDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LibraryDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LibraryDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LibraryDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LibraryDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LibraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LibraryDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibraryDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LibraryDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibraryDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LibraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibraryDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibraryDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibraryDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LibraryDB] SET  MULTI_USER 
GO

ALTER DATABASE [LibraryDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibraryDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibraryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LibraryDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LibraryDB] SET QUERY_STORE = OFF
GO

USE [LibraryDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [LibraryDB] SET  READ_WRITE 
GO
USE [LibraryDB]
GO

/****** Object:  Table [dbo].[Author]    Script Date: 07/04/2019 09:03:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Author](
	[Id] [int] IDENTITY(100,10) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Nationality] [nvarchar](50) NULL,
	[BirthDay] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[Book](
	[IsbnCode] [nvarchar](10) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[CoverImage] [varbinary](max) NULL,
	[NbrPages] [int] NULL,
	[ReleaseDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IsbnCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


CREATE TABLE [dbo].[BookAuthors](
	[IsbnCode] [nvarchar](10) NOT NULL,
	[IdAuthor] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IsbnCode] ASC,
	[IdAuthor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BookAuthors]  WITH CHECK ADD  CONSTRAINT [FK_Author_ToBookAuthor1] FOREIGN KEY([IdAuthor])
REFERENCES [dbo].[Author] ([Id])
GO

ALTER TABLE [dbo].[BookAuthors] CHECK CONSTRAINT [FK_Author_ToBookAuthor1]
GO

ALTER TABLE [dbo].[BookAuthors]  WITH CHECK ADD  CONSTRAINT [FK_Book_ToBookAuthor1] FOREIGN KEY([IsbnCode])
REFERENCES [dbo].[Book] ([IsbnCode])
GO

ALTER TABLE [dbo].[BookAuthors] CHECK CONSTRAINT [FK_Book_ToBookAuthor1]
GO



